# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:8.9
        environment:
          - DATABASE_URL=postgres://ubuntu:@127.0.0.1:5432/caffee_test
          - REDIS_URL=redis://localhost:6379
      - image: postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=caffee_test
      - image: redis:3.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      - run: yarn lint:strict
