export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const PRODUCT_SET_PRODUCT_IDS = 'PRODUCT_SET_PRODUCT_IDS';
export const PRODUCT_SET_PRODUCT_ID = 'PRODUCT_SET_PRODUCT_ID';

export const ADD_ENTITIES = 'ADD_ENTITIES';
