export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_TEST_REQUEST = 'AUTH_TEST_REQUEST';
export const AUTH_TEST_FAILURE = 'AUTH_TEST_FAILURE';
export const AUTH_TEST_SUCCESS = 'AUTH_TEST_SUCCESS';
